"""Writer stage: scenario + brief -> article draft + post draft.

Drives the writer from prompts/writer.md via llm.complete_json with length
limits from cfg["limits"], keeping the signature and adhering to facts.
"""
from __future__ import annotations

import json
from pathlib import Path

from src.db import save_artifact
from src.schemas import Brief, Draft, Scenario

PROMPT_PATH = Path(__file__).resolve().parent.parent.parent / "prompts" / "writer.md"


def run_writer(scenario: Scenario, brief: Brief, cfg: dict, llm, conn=None) -> tuple[Draft, Draft]:
    """Returns article + post drafts generated by LLM based on Brief and Scenario."""

    prompt_path = Path("prompts/writer.md")
    if not prompt_path.exists():
        raise FileNotFoundError(f"Prompt file not found: {prompt_path}")

    system_prompt_template = prompt_path.read_text(encoding="utf-8")

    limits = cfg.get("limits", {})
    article_chars = limits.get("article_chars", [2000, 4000])
    post_words = limits.get("post_words", [100, 200])

    system_prompt = system_prompt_template.replace("{article_min}", str(article_chars[0]))
    system_prompt = system_prompt.replace("{article_max}", str(article_chars[1]))
    system_prompt = system_prompt.replace("{post_min}", str(post_words[0]))
    system_prompt = system_prompt.replace("{post_max}", str(post_words[1]))

    user_prompt = (
        f"СЦЕНАРИЙ:\n"
        f"Тема: {scenario.topic}\n"
        f"Ракурс: {scenario.angle}\n"
        f"Подсказка: {scenario.brief_hint}\n\n"
        f"БРИФ (факты для использования):\n"
        f"Общие факты: {brief.facts}\n"
        f"Подтверждено: {brief.confirmed}\n"
        f"Не подтверждено (не утверждать как факт): {brief.not_confirmed}\n"
        f"Цитаты: {brief.quotes}\n"
    )

    raw_response = llm.complete_json(
        system_prompt=system_prompt,
        user_prompt=user_prompt
    )

    if isinstance(raw_response, str):
        try:
            data = json.loads(raw_response)
        except json.JSONDecodeError as e:
            raise ValueError(f"LLM returned invalid JSON: {raw_response}") from e
    else:
        data = raw_response

    article_data = data.get("article", {})
    post_data = data.get("post", {})

    article = Draft(
        kind="article",
        title=article_data.get("title", f"Статья: {scenario.topic}"),
        body=article_data.get("body", "")
    )
    post = Draft(
        kind="post",
        title=post_data.get("title", f"Пост: {scenario.topic}"),
        body=post_data.get("body", "")
    )

    if conn is not None:
        save_artifact(
            conn,
            scenario_id=scenario.idx,
            kind="draft_article",
            content=article.model_dump_json()
        )
        save_artifact(
            conn,
            scenario_id=scenario.idx,
            kind="draft_post",
            content=post.model_dump_json()
        )

    return article, post
